name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: 'ubuntu-latest'
   
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v2.10.0

    - name: Download artifact

      uses: aochmann/actions-download-artifact@1.0.4
      with:
        name: app

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: guntzbr
        password: ${{ secrets.PASS_DOCKER_HUB }}
    
    - name: Build and push Docker images00   
   
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: guntzbr/go_ci:${{ github.ref_name }}
